const fs=require('fs'),path=require('path'),root=path.resolve(__dirname,'..');
const src=fs.readFileSync(path.join(root,'index.html'),'utf8'),head=src.match(/[\s\S]*?<body>/i)[0],secs={};
for(const m of src.matchAll(/<section\b[\s\S]*?<\/section>/gi)){const id=m[0].match(/\bid="([^"]+)"/i)?.[1];if(id)secs[id]=m[0]}
const dest={home:'index.html',features:'features.html',pro:'pro.html',organizations:'organizations.html',support:'support.html',download:'download.html'};
function links(s){const map={'#home':'index.html','#features':'features.html','#pro':'pro.html','#organizations':'organizations.html','#support':'support.html','#download':'download.html','#purpose':'index.html#purpose','#how-it-works':'index.html#how-it-works','#next-up':'features.html#next-up','#account-types':'features.html#account-types','#safety':'support.html#safety','#faq':'support.html#faq'};return s.replace(/href="(#[^"]+)"/g,(w,a)=>map[a]?`href="${map[a]}"`:w)}
function nav(active){const a=(k,l)=>`<a href="${dest[k]}"${k===active?' class="active" aria-current="page"':''}>${l}</a>`;return `<a class="visually-hidden" href="#main">Skip to main content</a><header class="navbar" id="navbar"><div class="container"><a href="index.html" class="brand"><img src="assets/footy-status-header-logo.png" alt="Footy Status" width="134" height="53"></a><nav class="nav-links" aria-label="Primary">${a('home','Home')}${a('features','Features')}${a('pro','Footy Status Pro')}${a('organizations','Organizations')}${a('support','Support')}${a('download','Download')}</nav><div class="nav-actions"><a href="download.html" class="btn btn-primary btn-sm nav-cta nav-cta-desktop">Get the App</a><button class="nav-toggle" id="navToggle" aria-label="Toggle menu" aria-expanded="false" aria-controls="mobilePanel"><span></span><span></span><span></span></button></div></div></header><div class="mobile-panel" id="mobilePanel">${a('home','Home')}${a('features','Features')}${a('pro','Footy Status Pro')}${a('organizations','Organizations')}${a('support','Support')}${a('download','Download')}<a href="download.html" class="btn btn-primary">Get the App</a></div>`}
function foot(){return `<footer class="footer"><div class="container"><div class="footer-top"><div class="footer-brand"><a href="index.html" class="brand"><img src="assets/footy-status-header-logo.png" alt="Footy Status"></a><p>The complete soccer platform for every side of the game.</p></div><div class="footer-col"><h4>Pages</h4><ul><li><a href="index.html">Home</a></li><li><a href="features.html">Features</a></li><li><a href="pro.html">Footy Status Pro</a></li></ul></div><div class="footer-col"><h4>Community</h4><ul><li><a href="organizations.html">Organizations</a></li><li><a href="support.html">Support</a></li><li><a href="download.html">Download</a></li></ul></div><div class="footer-col"><h4>Contact</h4><ul><li><a href="mailto:footystatussupport@gmail.com">Email Support</a></li><li><a href="support.html#faq">FAQ</a></li></ul></div></div><div class="footer-bottom"><p>&copy; ${new Date().getFullYear()} Footy Status. All rights reserved.</p></div></div></footer><script src="js/main.js"></script></body></html>`}
const pages=[['index.html','home','Home',['home','purpose','how-it-works']],['features.html','features','Features',['features','next-up','account-types']],['pro.html','pro','Footy Status Pro',['pro']],['organizations.html','organizations','Organizations',['organizations']],['support.html','support','Support',['safety','support','faq']],['download.html','download','Download',['download']]];
for(const [file,key,title,ids] of pages){const h=head.replace(/<title>[\s\S]*?<\/title>/i,`<title>${title} — Footy Status</title>`),body=ids.map(id=>secs[id]).filter(Boolean).join('\n');fs.writeFileSync(path.join(root,file),`${h}${nav(key)}<main id="main" class="page-${key}">${links(body)}</main>${foot()}`,'utf8')}
const cssPath=path.join(root,'css','styles.css');let css=fs.readFileSync(cssPath,'utf8');const marker='/* multi-page navigation */';if(!css.includes(marker))css+=`\n${marker}\n.nav-links a.active{color:var(--red)}.nav-links a.active::after{right:0}.mobile-panel a.active{color:var(--red);font-weight:800}main:not(.page-home)>.section:first-child{padding-top:112px}.page-pro #pro,.page-organizations #organizations,.page-support #safety{min-height:calc(100vh - var(--nav-h))}\n`;fs.writeFileSync(cssPath,css,'utf8');
